In [2]:
import numpy as np
import scipy.ndimage
import scipy.sparse
import scipy.sparse.linalg

In [6]:
# Cone filter
def _cone_filter_matrix_3D(nelx, nely, nelz, radius, mask):
  x, y, z = np.meshgrid(np.arange(nelx), np.arange(nely), np.arange(nelz), indexing='ij')

  rows = []
  cols = []
  values = []
  r_bound = int(np.ceil(radius))
  for dx in range(-r_bound, r_bound+1):
    for dy in range(-r_bound, r_bound+1):
      for dz in range(-r_bound, r_bound+1):
        weight = np.maximum(0, radius - np.sqrt(dx**2 + dy**2 + dz**2))
        #weight = np.maximum(0, radius - np.sqrt(dx**2 + dy**2))
        row = x + nelx * y
        column = x + dx + nelx * (y + dy)
        value = np.broadcast_to(weight, x.shape)
        print(x,'+',nelx,'*',y,'=',row)

        # exclude cells beyond the boundary
        valid = (
            (mask > 0) &
            ((x+dx) >= 0) &
            ((x+dx) < nelx) &
            ((y+dy) >= 0) &
            ((y+dy) < nely) &
            ((z+dz) >= 0) &
            ((z+dz) < nelz)
        )
        rows.append(row[valid])
        cols.append(column[valid])
        values.append(value[valid])

  data = np.concatenate(values)
  i = np.concatenate(rows)
  j = np.concatenate(cols)
  return scipy.sparse.coo_matrix((data, (i, j)), (nelx * nely * nelz,) * 2)
  #return scipy.sparse.coo_matrix((data, (i, j)), (nelx * nely,) * 2)

In [7]:
def _cone_filter_matrix(nelx, nely, radius, mask):
  x, y = np.meshgrid(np.arange(nelx), np.arange(nely), indexing='ij')

  rows = []
  cols = []
  values = []
  r_bound = int(np.ceil(radius))
  for dx in range(-r_bound, r_bound+1):
    for dy in range(-r_bound, r_bound+1):
      weight = np.maximum(0, radius - np.sqrt(dx**2 + dy**2))
      row = x + nelx * y
      column = x + dx + nelx * (y + dy)
      value = np.broadcast_to(weight, x.shape)

      # exclude cells beyond the boundary
      valid = (
          (mask > 0) &
          ((x+dx) >= 0) &
          ((x+dx) < nelx) &
          ((y+dy) >= 0) &
          ((y+dy) < nely)
      )
      rows.append(row[valid])
      cols.append(column[valid])
      values.append(value[valid])

  data = np.concatenate(values)
  i = np.concatenate(rows)
  j = np.concatenate(cols)

  return scipy.sparse.coo_matrix((data, (i, j)), (nelx * nely,) * 2)

In [8]:
nelx = 1
nely = 2
nelz = 2
radius = 2
mask = 1

In [9]:
#result2D = _cone_filter_matrix(nelx, nely, radius, mask)
result3D = _cone_filter_matrix_3D(nelx, nely, nelz, radius, mask).row

[[[0 0]
  [0 0]]] + 1 * [[[0 0]
  [1 1]]] = [[[0 0]
  [1 1]]]
[[[0 0]
  [0 0]]] + 1 * [[[0 0]
  [1 1]]] = [[[0 0]
  [1 1]]]
[[[0 0]
  [0 0]]] + 1 * [[[0 0]
  [1 1]]] = [[[0 0]
  [1 1]]]
[[[0 0]
  [0 0]]] + 1 * [[[0 0]
  [1 1]]] = [[[0 0]
  [1 1]]]
[[[0 0]
  [0 0]]] + 1 * [[[0 0]
  [1 1]]] = [[[0 0]
  [1 1]]]
[[[0 0]
  [0 0]]] + 1 * [[[0 0]
  [1 1]]] = [[[0 0]
  [1 1]]]
[[[0 0]
  [0 0]]] + 1 * [[[0 0]
  [1 1]]] = [[[0 0]
  [1 1]]]
[[[0 0]
  [0 0]]] + 1 * [[[0 0]
  [1 1]]] = [[[0 0]
  [1 1]]]
[[[0 0]
  [0 0]]] + 1 * [[[0 0]
  [1 1]]] = [[[0 0]
  [1 1]]]
[[[0 0]
  [0 0]]] + 1 * [[[0 0]
  [1 1]]] = [[[0 0]
  [1 1]]]
[[[0 0]
  [0 0]]] + 1 * [[[0 0]
  [1 1]]] = [[[0 0]
  [1 1]]]
[[[0 0]
  [0 0]]] + 1 * [[[0 0]
  [1 1]]] = [[[0 0]
  [1 1]]]
[[[0 0]
  [0 0]]] + 1 * [[[0 0]
  [1 1]]] = [[[0 0]
  [1 1]]]
[[[0 0]
  [0 0]]] + 1 * [[[0 0]
  [1 1]]] = [[[0 0]
  [1 1]]]
[[[0 0]
  [0 0]]] + 1 * [[[0 0]
  [1 1]]] = [[[0 0]
  [1 1]]]
[[[0 0]
  [0 0]]] + 1 * [[[0 0]
  [1 1]]] = [[[0 0]
  [1 1]]]
[[[0 0]


In [10]:
#print(result2D)
#print(result2D, '\n', 'ccccccccccccccccccccccccccccccccccc', '\n', result3D)

In [7]:
arr = np.array([10,20,40,46,33,14,12,46,52,30,59,18,11,22,30,2,11,58,22,72,12])
n = int(np.sqrt(len(arr)*2))

idx = np.tril_indices(n, k=0, m=n)
matrix = np.zeros((n,n)).astype(int)
matrix[idx] = arr
det = matrix.T
matrix = matrix + det

diag = np.diag(matrix)
diag0 = np.diag(diag)/2
matrix0 = matrix - diag0

print(matrix)
print(diag0)
print(matrix0)

[[20 20 46 12 59  2]
 [20 80 33 46 18 11]
 [46 33 28 52 11 58]
 [12 46 52 60 22 22]
 [59 18 11 22 60 72]
 [ 2 11 58 22 72 24]]
[[10.  0.  0.  0.  0.  0.]
 [ 0. 40.  0.  0.  0.  0.]
 [ 0.  0. 14.  0.  0.  0.]
 [ 0.  0.  0. 30.  0.  0.]
 [ 0.  0.  0.  0. 30.  0.]
 [ 0.  0.  0.  0.  0. 12.]]
[[10. 20. 46. 12. 59.  2.]
 [20. 40. 33. 46. 18. 11.]
 [46. 33. 14. 52. 11. 58.]
 [12. 46. 52. 30. 22. 22.]
 [59. 18. 11. 22. 30. 72.]
 [ 2. 11. 58. 22. 72. 12.]]


In [8]:
"""Stiffness Matrix"""

import autograd.numpy as np

young = 1
poisson = 0.3

e, nu = young, poisson
ke = np.multiply( e/(1+nu)/(2*nu-1)/144, ([-32,-6,-6,8,6,6,10,6,3,-4,-6,-3,-4,-3,-6,10,
    3,6,8,3,3,4,-3,-3, -32,-6,-6,-4,-3,6,10,3,6,8,6,-3,-4,-6,-3,4,-3,3,8,3,
    3,10,6,-32,-6,-3,-4,-3,-3,4,-3,-6,-4,6,6,8,6,3,10,3,3,8,3,6,10,-32,6,6,
    -4,6,3,10,-6,-3,10,-3,-6,-4,3,6,4,3,3,8,-3,-3,-32,-6,-6,8,6,-6,10,3,3,4,
    -3,3,-4,-6,-3,10,6,-3,8,3,-32,3,-6,-4,3,-3,4,-6,3,10,-6,6,8,-3,6,10,-3,
    3,8,-32,-6,6,8,6,-6,8,3,-3,4,-3,3,-4,-3,6,10,3,-6,-32,6,-6,-4,3,3,8,-3,
    3,10,-6,-3,-4,6,-3,4,3,-32,6,3,-4,-3,-3,8,-3,-6,10,-6,-6,8,-6,-3,10,-32,
    6,-6,4,3,-3,8,-3,3,10,-3,6,-4,3,-6,-32,6,-3,10,-6,-3,8,-3,3,4,3,3,-4,6,
    -32,3,-6,10,3,-3,8,6,-3,10,6,-6,8,-32,-6,6,8,6,-6,10,6,-3,-4,-6,3,-32,6,
    -6,-4,3,6,10,-3,6,8,-6,-32,6,3,-4,3,3,4,3,6,-4,-32,6,-6,-4,6,-3,10,-6,3,
    -32,6,-6,8,-6,-6,10,-3,-32,-3,6,-4,-3,3,4,-32,-6,-6,8,6,6,-32,-6,-6,-4,
    -3,-32,-6,-3,-4,-32,6,6,-32,-6,-32] + np.multiply(nu, [48,0,0,0,-24,-24,-12,0,-12,0,
    24,0,0,0,24,-12,-12,0,-12,0,0,-12,12,12,48,0,24,0,0,0,-12,-12,-24,0,-24,
    0,0,24,12,-12,12,0,-12,0,-12,-12,0,48,24,0,0,12,12,-12,0,24,0,-24,-24,0,
    0,-12,-12,0,0,-12,-12,0,-12,48,0,0,0,-24,0,-12,0,12,-12,12,0,0,0,-24,
    -12,-12,-12,-12,0,0,48,0,24,0,-24,0,-12,-12,-12,-12,12,0,0,24,12,-12,0,
    0,-12,0,48,0,24,0,-12,12,-12,0,-12,-12,24,-24,0,12,0,-12,0,0,-12,48,0,0,
    0,-24,24,-12,0,0,-12,12,-12,0,0,-24,-12,-12,0,48,0,24,0,0,0,-12,0,-12,
    -12,0,0,0,-24,12,-12,-12,48,-24,0,0,0,0,-12,12,0,-12,24,24,0,0,12,-12,
    48,0,0,-12,-12,12,-12,0,0,-12,12,0,0,0,24,48,0,12,-12,0,0,-12,0,-12,-12,
    -12,0,0,-24,48,-12,0,-12,0,0,-12,0,12,-12,-24,24,0,48,0,0,0,-24,24,-12,
    0,12,0,24,0,48,0,24,0,0,0,-12,12,-24,0,24,48,-24,0,0,-12,-12,-12,0,-24,
    0,48,0,0,0,-24,0,-12,0,-12,48,0,24,0,24,0,-12,12,48,0,-24,0,12,-12,-12,
    48,0,0,0,-24,-24,48,0,24,0,0,48,24,0,0,48,0,0,48,0,48])))

n = int(np.sqrt(len(ke)*2))
idx = np.triu_indices(n, k=0, m=n)
matrix = np.zeros((n,n)).astype(float)

matrix[idx] = ke
det = matrix.T
matrix = matrix + det

diag = np.diag(matrix)
diag0 = np.diag(diag)/2
matrix0 = matrix - diag0

#print(matrix)
#print(diag0)
print(matrix0)

[[ 0.23504274  0.08012821  0.08012821 -0.10683761  0.01602564  0.01602564
  -0.08547009 -0.08012821  0.00801282  0.0534188  -0.01602564  0.0400641
   0.0534188   0.0400641  -0.01602564 -0.08547009  0.00801282 -0.08012821
  -0.05876068 -0.0400641  -0.0400641  -0.00534188 -0.00801282 -0.00801282]
 [ 0.08012821  0.23504274  0.08012821 -0.01602564  0.0534188   0.0400641
  -0.08012821 -0.08547009  0.00801282  0.01602564 -0.10683761  0.01602564
   0.0400641   0.0534188  -0.01602564 -0.00801282 -0.00534188 -0.00801282
  -0.0400641  -0.05876068 -0.0400641   0.00801282 -0.08547009 -0.08012821]
 [ 0.08012821  0.08012821  0.23504274 -0.01602564  0.0400641   0.0534188
  -0.00801282 -0.00801282 -0.00534188  0.0400641  -0.01602564  0.0534188
   0.01602564  0.01602564 -0.10683761 -0.08012821  0.00801282 -0.08547009
  -0.0400641  -0.0400641  -0.05876068  0.00801282 -0.08012821 -0.08547009]
 [-0.10683761 -0.01602564 -0.01602564  0.23504274 -0.08012821 -0.08012821
   0.0534188   0.01602564 -0.0400641  -

In [76]:
young = 1
poisson = 0.3

e, nu = young, poisson
k = np.array([1/2-nu/6, 1/8+nu/8, -1/4-nu/12, -1/8+3*nu/8,
                -1/4+nu/12, -1/8-nu/8, nu/6, 1/8-3*nu/8])

ke = e/(1-nu**2)*np.array([[k[0], k[1], k[2], k[3], k[4], k[5], k[6], k[7]],
                               [k[1], k[0], k[7], k[6], k[5], k[4], k[3], k[2]],
                               [k[2], k[7], k[0], k[5], k[6], k[3], k[4], k[1]],
                               [k[3], k[6], k[5], k[0], k[7], k[2], k[1], k[4]],
                               [k[4], k[5], k[6], k[7], k[0], k[1], k[2], k[3]],
                               [k[5], k[4], k[3], k[2], k[1], k[0], k[7], k[6]],
                               [k[6], k[3], k[4], k[1], k[2], k[7], k[0], k[5]],
                               [k[7], k[2], k[1], k[4], k[3], k[6], k[5], k[0]]
                              ])
print(ke.dtype)


float64
